_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.12.9
            "5": 0.19.6
            "6": 4.48.3
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
